import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { productService } from '../../../services/productService';
import { CheckCircle2, Globe, ArrowLeft, Upload, X, Zap } from 'lucide-react';
import { toast } from 'sonner';


const AddProductPage = () => {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [success, setSuccess] = useState(false);

    const [formData, setFormData] = useState({
        title: '',
        brand: '',
        price: '',
        category: 'Men',
        description: '',
        discountPercentage: '',
        imageUrl: ''
    });
    const [isConverting, setIsConverting] = useState(false);
    const [uploadMode, setUploadMode] = useState<'library' | 'url'>('library');

    const compressAndSetImage = (file: File) => {
        setIsConverting(true);
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = (event) => {
            const img = new Image();
            img.src = event.target?.result as string;
            img.onload = () => {
                const canvas = document.createElement('canvas');
                const MAX_WIDTH = 800;
                const MAX_HEIGHT = 1000;
                let width = img.width;
                let height = img.height;

                if (width > height) {
                    if (width > MAX_WIDTH) {
                        height *= MAX_WIDTH / width;
                        width = MAX_WIDTH;
                    }
                } else {
                    if (height > MAX_HEIGHT) {
                        width *= MAX_HEIGHT / height;
                        height = MAX_HEIGHT;
                    }
                }
                canvas.width = width;
                canvas.height = height;
                const ctx = canvas.getContext('2d');
                ctx?.drawImage(img, 0, 0, width, height);

                // Use a lower quality to ensure it fits in Firestore (under 1MB)
                const dataUrl = canvas.toDataURL('image/jpeg', 0.6);
                setFormData(prev => ({ ...prev, imageUrl: dataUrl }));
                setIsConverting(false);
                toast.success("Image optimized & ready!");
            };
        };
        reader.onerror = () => {
            setIsConverting(false);
            toast.error("Failed to read file");
        };
    };

    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;
        compressAndSetImage(file);
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // If using URL mode, ensure it starts with http
        if (uploadMode === 'url' && !formData.imageUrl.startsWith('http')) {
            toast.error("Please provide a valid image URL starting with http");
            return;
        }
        // If using library mode, ensure an image is selected
        if (uploadMode === 'library' && !formData.imageUrl) {
            toast.error("Please select an image from your library");
            return;
        }

        setLoading(true);
        try {
            await productService.addProduct({
                id: '', // Will be generated by Firestore
                title: formData.title,
                brand: formData.brand,
                price: parseFloat(formData.price),
                category: formData.category,
                description: formData.description,
                image: formData.imageUrl,
                rating: {
                    rate: parseFloat((Math.random() * 2 + 3).toFixed(1)), // Mock realistic rating
                    count: Math.floor(Math.random() * 200) + 50
                },
                discountPercentage: formData.discountPercentage ? parseFloat(formData.discountPercentage) : undefined
            });

            toast.success("Product published live to Firebase!");
            setSuccess(true);
            setTimeout(() => navigate('/products'), 2000);
        } catch (error: any) {
            console.error(error);
            toast.error(error.message || "Failed to add product. Check your database rules.");
        } finally {
            setLoading(false);
        }
    };

    if (success) {
        return (
            <div className="min-h-screen flex items-center justify-center p-4">
                <div className="text-center animate-in fade-in zoom-in duration-300">
                    <CheckCircle2 className="w-20 h-20 text-green-500 mx-auto mb-6" />
                    <h2 className="text-3xl font-bold mb-2">Success!</h2>
                    <p className="text-gray-500 text-lg">Product is now live in your store.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-6xl mx-auto px-4 py-10">
            <div className="flex items-center gap-4 mb-8">
                <button onClick={() => navigate('/admin')} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                    <ArrowLeft className="w-6 h-6 text-gray-600" />
                </button>
                <h1 className="text-3xl font-bold">Add New Product</h1>
            </div>

            <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-10">
                {/* Image Preview Area */}
                <div className="lg:col-span-1 space-y-6">
                    <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                        <div className="flex justify-between items-center mb-4">
                            <label className="text-sm font-bold text-gray-700">Media Preview</label>
                            <div className="flex bg-gray-100 p-1 rounded-lg">
                                <button
                                    type="button"
                                    onClick={() => setUploadMode('library')}
                                    className={`px-3 py-1 text-[10px] font-black rounded-md transition-all ${uploadMode === 'library' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-400'}`}
                                >LIBRARY</button>
                                <button
                                    type="button"
                                    onClick={() => setUploadMode('url')}
                                    className={`px-3 py-1 text-[10px] font-black rounded-md transition-all ${uploadMode === 'url' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-400'}`}
                                >URL</button>
                            </div>
                        </div>

                        <div className="aspect-[3/4] rounded-xl overflow-hidden bg-gray-50 border-2 border-dashed border-gray-200 flex items-center justify-center relative group">
                            {formData.imageUrl ? (
                                <>
                                    <img
                                        src={formData.imageUrl}
                                        alt="Preview"
                                        className="w-full h-full object-cover transition-opacity duration-300"
                                    />
                                    <button
                                        type="button"
                                        onClick={() => setFormData({ ...formData, imageUrl: '' })}
                                        className="absolute top-4 right-4 p-2 bg-white/90 rounded-full text-red-500 shadow-xl opacity-0 group-hover:opacity-100 transition-all active:scale-95"
                                    >
                                        <X className="w-4 h-4" />
                                    </button>
                                </>
                            ) : (
                                <div className="text-center p-6 w-full">
                                    {isConverting ? (
                                        <div className="space-y-4 px-10">
                                            <div className="w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin mx-auto"></div>
                                            <p className="text-[10px] font-black text-indigo-600 uppercase tracking-widest">Optimizing Media...</p>
                                        </div>
                                    ) : (
                                        uploadMode === 'library' ? (
                                            <label className="cursor-pointer block w-full group">
                                                <input type="file" accept="image/*" className="hidden" onChange={handleFileUpload} />
                                                <Upload className="w-12 h-12 text-gray-300 mx-auto mb-3 group-hover:text-indigo-600 transition-colors" />
                                                <p className="text-sm text-gray-400 group-hover:text-indigo-600 font-bold transition-colors">Select from Library</p>
                                                <p className="text-[10px] text-gray-300 mt-2 uppercase font-black tracking-widest leading-none">Bypasses Storage Limits <br /> Stores in Database</p>
                                            </label>
                                        ) : (
                                            <div className="px-6 space-y-4">
                                                <Globe className="w-12 h-12 text-gray-300 mx-auto" />
                                                <input
                                                    className="w-full p-3 bg-white border border-gray-200 rounded-xl text-xs outline-none focus:ring-2 focus:ring-indigo-600"
                                                    placeholder="Paste Image URL here..."
                                                    value={formData.imageUrl}
                                                    onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })}
                                                />
                                                <p className="text-[10px] text-gray-400 font-bold uppercase">Right-click image &gt; Copy Image Address</p>
                                            </div>
                                        )
                                    )}
                                </div>
                            )}
                        </div>
                        <p className="text-[10px] text-gray-400 mt-4 leading-relaxed font-bold uppercase tracking-widest italic">
                            * Using High-Speed Database Storage (Firestore Sync)
                        </p>
                    </div>
                </div>

                {/* Details Area */}
                <div className="lg:col-span-2 space-y-8 bg-white p-8 rounded-2xl border border-gray-100 shadow-sm">
                    <div className="space-y-6">
                        <div className="p-4 bg-indigo-50 border border-indigo-100 rounded-2xl flex items-center gap-4 mb-4">
                            <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center flex-shrink-0 text-white shadow-lg shadow-indigo-100">
                                <Zap className="w-5 h-5 fill-current" />
                            </div>
                            <div>
                                <h3 className="text-xs font-black text-indigo-600 uppercase tracking-widest italic">Database Sync Active</h3>
                                <p className="text-[10px] text-indigo-400 font-black uppercase tracking-tighter">Bypassing storage limits for instant uploads</p>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-2">Product Title*</label>
                            <input
                                required
                                className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                placeholder="e.g. Vintage Denim Jacket"
                                value={formData.title}
                                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Brand*</label>
                                <input
                                    required
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                    placeholder="Nike, Zara, etc."
                                    value={formData.brand}
                                    onChange={(e) => setFormData({ ...formData, brand: e.target.value })}
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Category*</label>
                                <select
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all cursor-pointer"
                                    value={formData.category}
                                    onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                                >
                                    <option>Men</option>
                                    <option>Women</option>
                                    <option>Kids</option>
                                    <option>Beauty</option>
                                </select>
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Price (₹)*</label>
                                <input
                                    type="number"
                                    required
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                    placeholder="1499"
                                    value={formData.price}
                                    onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Discount (%)</label>
                                <input
                                    type="number"
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                    placeholder="20"
                                    value={formData.discountPercentage}
                                    onChange={(e) => setFormData({ ...formData, discountPercentage: e.target.value })}
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-2">Product Description*</label>
                            <textarea
                                required
                                rows={4}
                                className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                placeholder="Describe the material, fit, and highlights..."
                                value={formData.description}
                                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                            />
                        </div>

                        <div className="flex flex-col md:flex-row gap-4 items-center mb-8">
                            <div className="flex-1 text-[10px] font-black text-gray-400 uppercase tracking-widest italic">
                                Optimized for Free Tier • Zero Cost Media
                            </div>
                            <Button
                                type="submit"
                                className="w-full md:w-auto bg-indigo-600 hover:bg-indigo-700 text-white px-10 py-4 rounded-xl shadow-lg shadow-indigo-200 transition-all font-bold uppercase tracking-widest text-xs"
                                loading={loading || isConverting}
                            >
                                Publish Product
                            </Button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    );
};

export default AddProductPage;
