import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { productService } from '../../../services/productService';
import { CheckCircle2, Globe, ArrowLeft, Upload, X, Zap } from 'lucide-react';
import { toast } from 'sonner';


const AddProductPage = () => {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [success, setSuccess] = useState(false);

    const [formData, setFormData] = useState({
        title: '',
        brand: '',
        price: '',
        category: 'Men',
        description: '',
        discountPercentage: '',
        imageUrl: ''
    });
    const [uploadMode, setUploadMode] = useState<'library' | 'url'>('library');
    const [selectedFile, setSelectedFile] = useState<File | null>(null);

    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        setSelectedFile(file);

        // Show local preview immediately
        const reader = new FileReader();
        reader.onload = (event) => {
            setFormData(prev => ({ ...prev, imageUrl: event.target?.result as string }));
        };
        reader.readAsDataURL(file);
        toast.info("Image selected for upload");
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // If using URL mode, ensure it starts with http
        if (uploadMode === 'url' && !formData.imageUrl.startsWith('http')) {
            toast.error("Please provide a valid image URL starting with http");
            return;
        }
        // If using library mode, ensure an image is selected
        if (uploadMode === 'library' && !formData.imageUrl) {
            toast.error("Please select an image from your library");
            return;
        }

        setLoading(true);
        try {
            let finalImageUrl = formData.imageUrl;

            // 1. If library mode and we have a file, upload it to Firebase Storage
            if (uploadMode === 'library' && selectedFile) {
                toast.loading("Uploading image to Cloud Storage...");
                finalImageUrl = await productService.uploadImage(selectedFile);
                toast.success("Image safely stored in Cloud!");
            }

            // 2. Save product metadata to Firestore
            await productService.addProduct({
                id: '', // Generated by Firestore
                title: formData.title,
                brand: formData.brand,
                price: parseFloat(formData.price),
                category: formData.category,
                description: formData.description,
                image: finalImageUrl,
                rating: {
                    rate: parseFloat((Math.random() * 2 + 3).toFixed(1)),
                    count: Math.floor(Math.random() * 200) + 50
                },
                discountPercentage: formData.discountPercentage ? parseFloat(formData.discountPercentage) : undefined
            });

            toast.success("Product published live to Store!");
            setSuccess(true);
            setTimeout(() => navigate('/admin'), 2000);
        } catch (error: any) {
            console.error(error);
            toast.error(error.message || "Failed to add product.");
        } finally {
            setLoading(false);
            toast.dismiss();
        }
    };

    // Cleanup: dismiss any lingering toasts when navigating away
    useEffect(() => {
        return () => {
            toast.dismiss();
        };
    }, []);

    if (success) {
        return (
            <div className="min-h-screen flex items-center justify-center p-4">
                <div className="text-center animate-in fade-in zoom-in duration-300">
                    <CheckCircle2 className="w-20 h-20 text-green-500 mx-auto mb-6" />
                    <h2 className="text-3xl font-bold mb-2">Success!</h2>
                    <p className="text-gray-500 text-lg">Product is now live in your store.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-6xl mx-auto px-4 py-10">
            <div className="flex items-center gap-4 mb-8">
                <button onClick={() => navigate('/admin')} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                    <ArrowLeft className="w-6 h-6 text-gray-600" />
                </button>
                <h1 className="text-3xl font-bold">Add New Product</h1>
            </div>

            <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-10">
                {/* Image Preview Area */}
                <div className="lg:col-span-1 space-y-6">
                    <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                        <div className="flex justify-between items-center mb-4">
                            <label className="text-sm font-bold text-gray-700">Media Preview</label>
                            <div className="flex bg-gray-100 p-1 rounded-lg">
                                <button
                                    type="button"
                                    onClick={() => setUploadMode('library')}
                                    className={`px-3 py-1 text-[10px] font-black rounded-md transition-all ${uploadMode === 'library' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-400'}`}
                                >LIBRARY</button>
                                <button
                                    type="button"
                                    onClick={() => setUploadMode('url')}
                                    className={`px-3 py-1 text-[10px] font-black rounded-md transition-all ${uploadMode === 'url' ? 'bg-white text-indigo-600 shadow-sm' : 'text-gray-400'}`}
                                >URL</button>
                            </div>
                        </div>

                        <div className="aspect-[3/4] rounded-xl overflow-hidden bg-gray-50 border-2 border-dashed border-gray-200 flex items-center justify-center relative group">
                            {formData.imageUrl ? (
                                <>
                                    <img
                                        src={formData.imageUrl}
                                        alt="Preview"
                                        className="w-full h-full object-cover transition-opacity duration-300"
                                    />
                                    <button
                                        type="button"
                                        onClick={() => setFormData({ ...formData, imageUrl: '' })}
                                        className="absolute top-4 right-4 p-2 bg-white/90 rounded-full text-red-500 shadow-xl opacity-0 group-hover:opacity-100 transition-all active:scale-95"
                                    >
                                        <X className="w-4 h-4" />
                                    </button>
                                </>
                            ) : (
                                <div className="text-center p-6 w-full">
                                    {uploadMode === 'library' ? (
                                        <label className="cursor-pointer block w-full group">
                                            <input type="file" accept="image/*" className="hidden" onChange={handleFileUpload} />
                                            <Upload className="w-12 h-12 text-gray-300 mx-auto mb-3 group-hover:text-indigo-600 transition-colors" />
                                            <p className="text-sm text-gray-400 group-hover:text-indigo-600 font-bold transition-colors">Select from Library</p>
                                            <p className="text-[10px] text-gray-300 mt-2 uppercase font-black tracking-widest leading-none">Bypasses Storage Limits <br /> Stores in Database</p>
                                        </label>
                                    ) : (
                                        <div className="px-6 space-y-4">
                                            <div className="w-16 h-16 bg-indigo-50 rounded-full flex items-center justify-center mx-auto mb-2">
                                                <Globe className="w-8 h-8 text-indigo-500" />
                                            </div>
                                            <input
                                                className="w-full p-4 bg-indigo-50/50 border border-indigo-100 rounded-xl text-xs outline-none focus:ring-2 focus:ring-indigo-600 font-bold placeholder:text-indigo-300 transition-all"
                                                placeholder="Paste Image URL from Unsplash..."
                                                value={formData.imageUrl}
                                                onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })}
                                            />
                                            <div className="space-y-1">
                                                <p className="text-[10px] text-indigo-500 font-black uppercase tracking-widest">Method 1: Direct Image Link</p>
                                                <p className="text-[9px] text-gray-400 font-bold uppercase italic">* Right-click &gt; Copy Image Address</p>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                        <p className="text-[10px] text-gray-400 mt-4 leading-relaxed font-bold uppercase tracking-widest italic border-t border-gray-50 pt-4">
                            * Cloudinary Active • 100% Free Hosting for Your Uploads
                        </p>
                    </div>
                </div>

                {/* Details Area */}
                <div className="lg:col-span-2 space-y-8 bg-white p-8 rounded-2xl border border-gray-100 shadow-sm">
                    <div className="space-y-6">
                        <div className="p-4 bg-indigo-50 border border-indigo-100 rounded-2xl flex items-center gap-4 mb-4">
                            <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center flex-shrink-0 text-white shadow-lg shadow-indigo-100">
                                <Zap className="w-5 h-5 fill-current" />
                            </div>
                            <div>
                                <h3 className="text-xs font-black text-indigo-600 uppercase tracking-widest italic">Cloud Storage Active</h3>
                                <p className="text-[10px] text-indigo-400 font-black uppercase tracking-tighter">Using official Firebase Storage for premium performance</p>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-2">Product Title*</label>
                            <input
                                required
                                className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                placeholder="e.g. Vintage Denim Jacket"
                                value={formData.title}
                                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Brand*</label>
                                <input
                                    required
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                    placeholder="Nike, Zara, etc."
                                    value={formData.brand}
                                    onChange={(e) => setFormData({ ...formData, brand: e.target.value })}
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Category*</label>
                                <select
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all cursor-pointer"
                                    value={formData.category}
                                    onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                                >
                                    <option value="Men">Men</option>
                                    <option value="Women">Women</option>
                                    <option value="Kids">Kids</option>
                                    <option value="Beauty & Skincare">Beauty & Skincare</option>
                                    <option value="Gadgets">Gadgets</option>
                                    <option value="Anime">Anime</option>
                                    <option value="Food & Grocery">Food & Grocery</option>
                                    <option value="Home Appliances">Home Appliances</option>
                                </select>
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Price (₹)*</label>
                                <input
                                    type="number"
                                    required
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                    placeholder="1499"
                                    value={formData.price}
                                    onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Discount (%)</label>
                                <input
                                    type="number"
                                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                    placeholder="20"
                                    value={formData.discountPercentage}
                                    onChange={(e) => setFormData({ ...formData, discountPercentage: e.target.value })}
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-2">Product Description*</label>
                            <textarea
                                required
                                rows={4}
                                className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:bg-white outline-none transition-all"
                                placeholder="Describe the material, fit, and highlights..."
                                value={formData.description}
                                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                            />
                        </div>

                        <div className="flex flex-col md:flex-row gap-4 items-center mb-8">
                            <div className="flex-1 text-[10px] font-black text-gray-400 uppercase tracking-widest italic">
                                Optimized for Free Tier • Zero Cost Media
                            </div>
                            <Button
                                type="submit"
                                className="w-full md:w-auto bg-indigo-600 hover:bg-indigo-700 text-white px-10 py-4 rounded-xl shadow-lg shadow-indigo-200 transition-all font-bold uppercase tracking-widest text-xs"
                                loading={loading}
                            >
                                Publish Product
                            </Button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    );
};

export default AddProductPage;
